"""empty message

Revision ID: 1a1d5ace2237
Revises: 9045dee245ad
Create Date: 2024-03-18 00:36:58.756020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1d5ace2237'
down_revision = '9045dee245ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_title', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_favorite_movie_title'), ['movie_title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_movie_title'))
        batch_op.drop_column('movie_title')

    # ### end Alembic commands ###
